// Generated by CoffeeScript 1.3.3
(function() {
  var SimpleDynamo, dynDB, _CONFIG, _ref, _ref1;

  _CONFIG = require("./config.js");

  if (((_ref = process.env) != null ? _ref.AWS_ACCESS_KEY_ID : void 0) != null) {
    _CONFIG.aws.accessKeyId = process.env.AWS_ACCESS_KEY_ID;
  }

  if (((_ref1 = process.env) != null ? _ref1.AWS_SECRET_ACCESS_KEY : void 0) != null) {
    _CONFIG.aws.secretAccessKey = process.env.AWS_SECRET_ACCESS_KEY;
  }

  SimpleDynamo = require("../lib/dynamo/");

  dynDB = null;

  describe("----- SETUP -----", function() {
    before(function(done) {
      dynDB = new SimpleDynamo(_CONFIG.aws, _CONFIG.tables);
      return done();
    });
    describe("Initialization", function() {
      return it("init table objects", function(done) {
        var _this = this;
        return dynDB.connect(function(err) {
          if (err) {
            throw err;
          }
          return done();
        });
      });
    });
    return describe("Create tables", function() {
      it("create a single table", function(done) {
        return dynDB.generate(_CONFIG.test.singleCreateTableTest, function(err) {
          if (err) {
            throw err;
          }
          return done();
        });
      });
      return it("create all missing tables", function(done) {
        return dynDB.generateAll(function(err) {
          if (err) {
            throw err;
          }
          return done();
        });
      });
    });
  });

}).call(this);
