// Generated by CoffeeScript 1.3.3
(function() {
  var SimpleDynamo, dynDB, _, _CONFIG, _ref, _ref1, _tables, _utils;

  _CONFIG = require("./config.js");

  _ = require("underscore");

  if (((_ref = process.env) != null ? _ref.AWS_ACCESS_KEY_ID : void 0) != null) {
    _CONFIG.aws.accessKeyId = process.env.AWS_ACCESS_KEY_ID;
  }

  if (((_ref1 = process.env) != null ? _ref1.AWS_SECRET_ACCESS_KEY : void 0) != null) {
    _CONFIG.aws.secretAccessKey = process.env.AWS_SECRET_ACCESS_KEY;
  }

  SimpleDynamo = require("../lib/dynamo/");

  dynDB = null;

  _tables = [];

  _utils = SimpleDynamo.utils;

  describe("----- TEARDOWN -----", function() {
    before(function(done) {
      dynDB = new SimpleDynamo(_CONFIG.aws, _CONFIG.tables);
      dynDB.connect(function(err) {
        if (err) {
          throw err;
        }
        dynDB.list(function(err, tables) {
          if (err) {
            throw err;
          }
          _tables = tables;
          return done();
        });
      });
    });
    return it("DESTROY test tables", function(done) {
      var aFn, tableName, _i, _len, _tbl;
      if (!_CONFIG.test.deleteTablesOnEnd) {
        done();
        console.log("DESTROY deactivated");
        return;
      }
      aFn = [];
      for (_i = 0, _len = _tables.length; _i < _len; _i++) {
        tableName = _tables[_i];
        _tbl = dynDB.get(tableName);
        if (_tbl) {
          aFn.push(_.bind(function(cba) {
            tableName = this.name;
            return this.destroy(function(err) {
              console.log("" + tableName + " deleted");
              if (err) {
                console.log(err);
              }
              _.delay(cba, 2000, err);
            });
          }, _tbl));
        }
      }
      _utils.runSeries(aFn, function(err) {
        if (_utils.checkArray(err)) {
          throw _.first(err);
        }
        done();
      });
    });
  });

}).call(this);
