// Generated by CoffeeScript 1.3.3
(function() {
  var exports;

  exports = module.exports = require("./manager");

  exports.version = '0.3.1';

  exports.Table = require("./table");

  exports.Attributes = require("./attributes");

  exports.utils = require("./utils");

}).call(this);
