// Generated by CoffeeScript 1.3.3
(function() {
  var Attributes, DynamoTable, ERRORMAPPING, EventEmitter, attributesHelper, utils, uuid, _,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __slice = [].slice;

  uuid = require('node-uuid');

  _ = require("underscore");

  Attributes = require("./attributes");

  attributesHelper = Attributes.helper;

  utils = require("./utils");

  EventEmitter = require("events").EventEmitter;

  module.exports = DynamoTable = (function(_super) {

    __extends(DynamoTable, _super);

    function DynamoTable(table, options) {
      var _this = this;
      this.options = options;
      this.scan = __bind(this.scan, this);

      this._getThroughput = __bind(this._getThroughput, this);

      this._getShema = __bind(this._getShema, this);

      this._generate = __bind(this._generate, this);

      this._checkSetOptions = __bind(this._checkSetOptions, this);

      this._convertValue = __bind(this._convertValue, this);

      this._defaultRangeKey = __bind(this._defaultRangeKey, this);

      this._defaultHashKey = __bind(this._defaultHashKey, this);

      this._createRangeKey = __bind(this._createRangeKey, this);

      this._createHashKey = __bind(this._createHashKey, this);

      this._createId = __bind(this._createId, this);

      this._validateHash = __bind(this._validateHash, this);

      this._deFixHash = __bind(this._deFixHash, this);

      this._fixHash = __bind(this._fixHash, this);

      this._dynamoItem2JSONSingle = __bind(this._dynamoItem2JSONSingle, this);

      this._dynamoItem2JSON = __bind(this._dynamoItem2JSON, this);

      this._del = __bind(this._del, this);

      this._create = __bind(this._create, this);

      this._update = __bind(this._update, this);

      this._mget = __bind(this._mget, this);

      this._get = __bind(this._get, this);

      this._isExistend = __bind(this._isExistend, this);

      this._getOptions = __bind(this._getOptions, this);

      this._fixCombinedHash = __bind(this._fixCombinedHash, this);

      this._error = __bind(this._error, this);

      this.destroy = __bind(this.destroy, this);

      this.find = __bind(this.find, this);

      this.del = __bind(this.del, this);

      this.set = __bind(this.set, this);

      this.mget = __bind(this.mget, this);

      this.get = __bind(this.get, this);

      this.meta = __bind(this.meta, this);

      this.generate = __bind(this.generate, this);

      this.init = __bind(this.init, this);

      this.mng = this.options.manager;
      this.defaults = this.options.defaults;
      this.external = this.options.external;
      this.__defineGetter__("name", function() {
        return _this._model_settings.name;
      });
      this.__defineGetter__("tableName", function() {
        return _this._model_settings.combineTableTo || _this._model_settings.name || null;
      });
      this.__defineGetter__("isCombinedTable", function() {
        return _this._model_settings.combineTableTo != null;
      });
      this.__defineGetter__("combinedHashDelimiter", function() {
        return "";
      });
      this.__defineGetter__("existend", function() {
        return _this.external != null;
      });
      this.__defineGetter__("hasRange", function() {
        var _ref, _ref1;
        if ((_ref = _this._model_settings) != null ? (_ref1 = _ref.rangeKey) != null ? _ref1.length : void 0 : void 0) {
          return true;
        } else {
          return false;
        }
      });
      this.__defineGetter__("hashKey", function() {
        var _ref;
        return ((_ref = _this._model_settings) != null ? _ref.hashKey : void 0) || null;
      });
      this.__defineGetter__("hashKeyType", function() {
        var _ref;
        if (_this.isCombinedTable) {
          return "S";
        } else {
          return ((_ref = _this._model_settings) != null ? _ref.hashKeyType : void 0) || "S";
        }
      });
      this.__defineGetter__("rangeKey", function() {
        var _ref;
        return ((_ref = _this._model_settings) != null ? _ref.rangeKey : void 0) || null;
      });
      this.__defineGetter__("rangeKeyType", function() {
        var _ref;
        if (_this.hasRange) {
          return ((_ref = _this._model_settings) != null ? _ref.rangeKeyType : void 0) || "N";
        } else {
          return null;
        }
      });
      this.__defineGetter__("overwriteExistingHash", function() {
        var _ref;
        if (((_ref = _this._model_settings) != null ? _ref.overwriteExistingHash : void 0) != null) {
          return _this._model_settings.overwriteExistingHash;
        } else if (_this.defaults.overwriteExistingHash != null) {
          return _this.defaults.overwriteExistingHash;
        } else {
          return false;
        }
      });
      this.init(table);
      return;
    }

    DynamoTable.prototype.init = function(table) {
      this._model_settings = table;
      this._attrs = new Attributes(table.attributes, this);
      if (this.isCombinedTable) {
        this._regexRemCT = new RegExp("^" + this.name, "i");
      }
    };

    DynamoTable.prototype.generate = function(cb) {
      var err;
      err = {};
      if (!(this.external != null)) {
        this._generate(cb);
      } else {
        this.emit("create-status", "already-active");
        cb(null, false);
      }
    };

    DynamoTable.prototype.meta = function(cb) {
      var _this = this;
      if (this._meta != null) {
        cb(null, this._meta);
      } else if (this._isExistend(cb)) {
        this.external.fetch(function(err, _meta) {
          if (err) {
            _this._error(cb, err);
          } else {
            _this._meta = _meta;
            cb(null, _meta);
          }
        });
      }
    };

    DynamoTable.prototype.get = function() {
      var args, cb, options, query, _i, _id,
        _this = this;
      args = 2 <= arguments.length ? __slice.call(arguments, 0, _i = arguments.length - 1) : (_i = 0, []), cb = arguments[_i++];
      if (this._isExistend(cb)) {
        options = null;
        switch (args.length) {
          case 1:
            _id = args[0];
            break;
          case 2:
            _id = args[0], options = args[1];
        }
        options = this._getOptions(options);
        query = this._deFixHash(_id, cb);
        if (query instanceof Error) {
          this._error(cb, query);
          return;
        }
        this._get(query, options, function(err, _item) {
          var _obj;
          if (err) {
            _this._error(cb, err);
          } else {
            if (_item) {
              _obj = _this._dynamoItem2JSON(_item, false);
              _this.emit("get", _obj);
              cb(null, _obj);
            } else {
              _this.emit("get-empty");
              cb(null, null);
            }
          }
        });
      }
    };

    DynamoTable.prototype.mget = function() {
      var args, cb, mQuery, options, query, _i, _id, _ids, _j, _len,
        _this = this;
      args = 2 <= arguments.length ? __slice.call(arguments, 0, _i = arguments.length - 1) : (_i = 0, []), cb = arguments[_i++];
      if (this._isExistend(cb)) {
        options = null;
        switch (args.length) {
          case 1:
            _ids = args[0];
            break;
          case 2:
            _ids = args[0], options = args[1];
        }
        options = this._getOptions(options);
        mQuery = [];
        for (_j = 0, _len = _ids.length; _j < _len; _j++) {
          _id = _ids[_j];
          query = this._deFixHash(_id, cb);
          if (query instanceof Error) {
            this._error(cb, query);
            return;
          } else {
            mQuery.push(query);
          }
        }
        this._mget(mQuery, options, function(err, _item) {
          var _obj;
          if (err) {
            _this._error(cb, err);
          } else {
            if (_item.length) {
              _obj = _this._dynamoItem2JSON(_item, false);
              _this.emit("mget", _obj);
              cb(null, _obj);
            } else {
              _this.emit("mget-empty");
              cb(null, []);
            }
          }
        });
      }
    };

    DynamoTable.prototype.set = function() {
      var args, attributes, cb, options, _create, _i, _id,
        _this = this;
      args = 2 <= arguments.length ? __slice.call(arguments, 0, _i = arguments.length - 1) : (_i = 0, []), cb = arguments[_i++];
      if (this._isExistend(cb)) {
        options = null;
        switch (args.length) {
          case 1:
            _create = true;
            _id = null;
            attributes = args[0];
            break;
          case 2:
            if (_.isString(args[0]) || _.isNumber(args[0]) || _.isArray(args[0])) {
              _create = false;
              _id = args[0], attributes = args[1];
            } else {
              _create = true;
              _id = null;
              attributes = args[0], options = args[1];
            }
            break;
          case 3:
            _create = false;
            _id = args[0], attributes = args[1], options = args[2];
        }
        options = this._getOptions(options);
        this._attrs.validateAttributes(_create, attributes, function(err, attributes) {
          if (err) {
            return _this._error(cb, err);
          } else {
            if (_create) {
              return _this._create(attributes, options, function(err, _item) {
                var _obj, _ref;
                if (err) {
                  _this._error(cb, err);
                } else {
                  _obj = _this._dynamoItem2JSON(_item, true);
                  _this.emit("create", _obj);
                  if (options != null ? (_ref = options.fields) != null ? _ref.length : void 0 : void 0) {
                    _obj = utils.reduceObj(_obj, options != null ? options.fields : void 0);
                  }
                  cb(null, _obj);
                }
              });
            } else {
              return _this._update(_id, attributes, options, function(err, item) {
                var _obj, _reducedItem, _ref;
                if (err) {
                  _this._error(cb, err);
                } else {
                  _obj = _this._dynamoItem2JSON(item, true);
                  _this.emit("update", _obj);
                  if (options != null ? (_ref = options.fields) != null ? _ref.length : void 0 : void 0) {
                    _reducedItem = utils.reduceObj(_obj, options.fields);
                  }
                  cb(null, _reducedItem || _obj);
                }
              });
            }
          }
        });
      }
    };

    DynamoTable.prototype.del = function(_id, cb) {
      var args, options, query, _i,
        _this = this;
      args = 2 <= arguments.length ? __slice.call(arguments, 0, _i = arguments.length - 1) : (_i = 0, []), cb = arguments[_i++];
      _id = args[0], options = args[1];
      options || (options = {});
      if (this._isExistend(cb)) {
        query = this._deFixHash(_id);
        if (query instanceof Error) {
          this._error(cb, query);
        } else {
          this._del(query, options, function(err, success) {
            if (err) {
              _this._error(cb, err);
            } else {
              _this.emit("delete", success);
              cb(null, success);
            }
          });
        }
      }
    };

    DynamoTable.prototype.find = function() {
      var args, cb, isScan, options, query, startAt, _fetchOpts, _fnHandle, _i, _op, _query, _ref, _ref1, _val, _x,
        _this = this;
      args = 2 <= arguments.length ? __slice.call(arguments, 0, _i = arguments.length - 1) : (_i = 0, []), cb = arguments[_i++];
      if (this._isExistend(cb)) {
        options = null;
        startAt = null;
        query = {};
        switch (args.length) {
          case 1:
            query = args[0];
            break;
          case 2:
            query = args[0], _x = args[1];
            if (_.isString(_x) || _.isNumber(_x)) {
              startAt = _x;
            } else {
              options = _x;
            }
            break;
          case 3:
            query = args[0], startAt = args[1], options = args[2];
        }
        options = this._getOptions(options);
        if (startAt != null) {
          startAt = this._deFixHash(startAt);
          if (startAt instanceof Error) {
            this._error(cb, startAt);
            return;
          }
        }
        if (this.isCombinedTable) {
          if (query != null ? query[this.hashKey] : void 0) {
            _op = _.first(Object.keys(query[this.hashKey]));
            _val = query[this.hashKey][_op];
            _val = ((_ref = this._deFixHash(_val)) != null ? _ref[this.hashKey] : void 0) || _val;
            if (_val instanceof Error) {
              this._error(cb, _val);
              return;
            }
            switch (_op) {
              case "==":
                _val = _val;
            }
            query[this.hashKey][_op] = _val;
          } else {
            query[this.hashKey] = {
              "startsWith": this.name
            };
          }
        }
        if (this._isExistend(cb)) {
          _ref1 = this._attrs.getQuery(this.external, query, startAt, options), _query = _ref1[0], isScan = _ref1[1];
          _fnHandle = function(err, _items) {
            if (err) {
              _this._error(cb, err);
            } else {
              cb(null, _this._dynamoItem2JSON(_items, false));
            }
          };
          if (isScan) {
            _query.fetch(_fnHandle);
          } else {
            _fetchOpts = {
              consistent: options.consistent
            };
            _query.fetch(_fetchOpts, _fnHandle);
          }
        }
      }
    };

    DynamoTable.prototype.destroy = function(cb) {
      if (this._isExistend(cb)) {
        return this.external.destroy(cb);
      }
    };

    DynamoTable.prototype._error = function(cb, err) {
      var error, _err;
      if (ERRORMAPPING[err.name] != null) {
        _err = ERRORMAPPING[err.name];
        error = new Error;
        error.name = _err.name;
        error.message = _err.message;
        cb(error);
      } else {
        cb(err);
      }
    };

    DynamoTable.prototype._fixCombinedHash = function(hash) {
      var _i;
      if (this.isCombinedTable) {
        _i = this.name.length;
        if (hash.slice(0, (_i - 1) + 1 || 9e9) === this.name) {
          return hash.slice(_i);
        } else {
          return hash;
        }
      } else {
        return hash;
      }
    };

    DynamoTable.prototype._getOptions = function(options) {
      var _defOpt;
      if (options == null) {
        options = {};
      }
      _defOpt = {
        fields: this._model_settings.defaultfields != null ? this._model_settings.defaultfields : void 0,
        overwriteExistingHash: this.overwriteExistingHash,
        consistent: this._model_settings.consistent != null ? this._model_settings.consistent : false,
        forward: this._model_settings.forward != null ? this._model_settings.forward : true,
        conditionals: null
      };
      return _.extend(_defOpt, options || {});
    };

    DynamoTable.prototype._isExistend = function(cb) {
      var error;
      if (this.existend) {
        return true;
      } else {
        if (_.isFunction(cb)) {
          error = new Error;
          error.name = "table-not-created";
          error.message = "Table '" + this.tableName + "' not existend at AWS. please run `Table.generate()` or `Manager.generateAll()` first.";
          this._error(cb, error);
        }
        return false;
      }
    };

    DynamoTable.prototype._get = function(query, options, cb) {
      var _fetchOpts, _item, _ref,
        _this = this;
      _item = this.external.get(query);
      if (options != null ? (_ref = options.fields) != null ? _ref.length : void 0 : void 0) {
        _item.get(options.fields);
      }
      _fetchOpts = {
        consistent: options.consistent
      };
      _item.fetch(_fetchOpts, function(err, item) {
        if (err) {
          cb(err);
        } else {
          cb(null, item);
        }
      });
    };

    DynamoTable.prototype._mget = function(mquery, options, cb) {
      var _batch, _self,
        _this = this;
      _self = this;
      _batch = this.mng.client.get(function() {
        var _ref;
        if (options != null ? (_ref = options.fields) != null ? _ref.length : void 0 : void 0) {
          return this.get(_self.tableName, mquery, options.fields);
        } else {
          return this.get(_self.tableName, mquery);
        }
      });
      _batch.fetch(function(err, items) {
        if (err) {
          cb(err);
        } else {
          cb(null, items[_this.tableName] || []);
        }
      });
    };

    DynamoTable.prototype._update = function(id, attributes, options, cb) {
      var item, _id, _upd,
        _this = this;
      if (options == null) {
        options = {};
      }
      _id = this._deFixHash(id);
      if (_id instanceof Error) {
        this._error(cb, _id);
        return;
      }
      item = this.external.get(_id);
      _upd = item.update(this._attrs.updateAttrsFn(attributes, options));
      _upd.returning("ALL_NEW");
      _upd = this._checkSetOptions("update", _upd, attributes, options);
      if (_upd.AttributeUpdates != null) {
        _upd.save(function(err, _saved) {
          if (err) {
            cb(err);
          } else {
            cb(null, _saved.Attributes || {});
          }
        });
      } else {
        cb(null, null);
      }
    };

    DynamoTable.prototype._create = function(attributes, options, cb) {
      var _this = this;
      if (attributes == null) {
        attributes = {};
      }
      this._createId(attributes, function(err, attributes) {
        var _upd;
        if (err) {
          cb(err);
        } else {
          _upd = _this.external.put(attributes);
          _upd = _this._checkSetOptions("create", _upd, attributes, options);
          _upd.save(function(err) {
            if (err) {
              cb(err);
            } else {
              cb(null, _upd);
            }
          });
        }
      });
    };

    DynamoTable.prototype._del = function(query, options, cb) {
      var _del,
        _this = this;
      _del = this.external.get(query);
      _del.returning("ALL_OLD");
      _del = this._checkSetOptions("update", _del, {}, options);
      _del.destroy(function(err, item) {
        if (err) {
          cb(err);
        } else {
          cb(null, item || null);
        }
      });
    };

    DynamoTable.prototype._dynamoItem2JSON = function(items, convertAttrs) {
      var idx, item, _i, _len;
      if (convertAttrs == null) {
        convertAttrs = false;
      }
      if (_.isArray(items)) {
        for (idx = _i = 0, _len = items.length; _i < _len; idx = ++_i) {
          item = items[idx];
          items[idx] = this._dynamoItem2JSONSingle(item, convertAttrs);
        }
        return items;
      } else {
        return this._dynamoItem2JSONSingle(items, convertAttrs);
      }
    };

    DynamoTable.prototype._dynamoItem2JSONSingle = function(item, convertAttrs) {
      var _obj;
      if (convertAttrs == null) {
        convertAttrs = false;
      }
      if (convertAttrs) {
        _obj = attributesHelper.dyn2obj((item != null ? item.Item : void 0) || item);
      } else {
        _obj = item;
      }
      return this._fixHash(_obj);
    };

    DynamoTable.prototype._fixHash = function(attrs) {
      return attrs;
    };

    DynamoTable.prototype._deFixHash = function(attrs) {
      var error, _attrs, _h, _hName, _hType, _r, _rName, _rType, _ref;
      if (_.isString(attrs) || _.isNumber(attrs) || _.isArray(attrs)) {
        _hName = this.hashKey;
        _attrs = {};
        _attrs[_hName] = _.clone(attrs);
      } else {
        _attrs = _.clone(attrs);
      }
      if (this.hasRange) {
        _hType = this.hashKeyType;
        _rName = this.rangeKey;
        _rType = this.rangeKeyType;
        if (!_.isArray(_attrs[_hName])) {
          error = new Error;
          error.name = "invalid-range-call";
          error.message = "If you try to access a hash/range item you have to pass a Array of `[hash,range]` as id.";
          return error;
        }
        _ref = _attrs[_hName], _h = _ref[0], _r = _ref[1];
        _attrs[_hName] = this._convertValue(_h, _hType);
        _attrs[_rName] = this._convertValue(_r, _rType);
      }
      return _attrs;
    };

    DynamoTable.prototype._validateHash = function(hash) {
      var _l, _pre;
      _pre = this.name + this.combinedHashDelimiter;
      _l = _pre.length;
      return hash.slice(0, _l) === _pre;
    };

    DynamoTable.prototype._createId = function(attributes, cb) {
      var _this = this;
      this._createHashKey(attributes, function(attributes) {
        var error;
        if (_this.isCombinedTable) {
          if (!_this._validateHash(attributes[_this.hashKey])) {
            error = new Error;
            error.name = "combined-hash-invalid";
            error.message = "The hash of a combined-table has to start with the `name` of this table defined in the configuartion. Please try `" + (_this.name + _this.combinedHashDelimiter + attributes[_this.hashKey]) + "`";
            _this._error(cb, error);
            return;
          }
        }
        if (_this.hasRange) {
          _this._createRangeKey(attributes, function(attributes) {
            cb(null, attributes);
          });
        } else {
          cb(null, attributes);
        }
      });
    };

    DynamoTable.prototype._createHashKey = function(attributes, cbH) {
      var _hName, _hType,
        _this = this;
      _hName = this.hashKey;
      _hType = this.hashKeyType;
      if (this._model_settings.fnCreateHash && _.isFunction(this._model_settings.fnCreateHash)) {
        this._model_settings.fnCreateHash(attributes, function(_hash) {
          attributes[_hName] = _this._convertValue(_hash, _hType);
          cbH(attributes);
        });
      } else if (attributes[_hName] != null) {
        attributes[_hName] = this._convertValue(attributes[_hName], _hType);
        cbH(attributes);
      } else {
        attributes[_hName] = this._convertValue(this._defaultHashKey(), _hType);
        cbH(attributes);
      }
    };

    DynamoTable.prototype._createRangeKey = function(attributes, cbR) {
      var _rName, _rType,
        _this = this;
      _rName = this.rangeKey;
      _rType = this.rangeKeyType;
      if (this._model_settings.fnCreateRange && _.isFunction(this._model_settings.fnCreateRange)) {
        this._model_settings.fnCreateRange(attributes, function(__range) {
          attributes[_rName] = _this._convertValue(__range, _rType);
          cbR(attributes);
        });
      } else if (attributes[_rName] != null) {
        attributes[_rName] = this._convertValue(attributes[_rName], _rType);
        cbR(attributes);
      } else {
        attributes[_rName] = this._convertValue(this._defaultRangeKey(), _rType);
        cbR(attributes);
      }
    };

    DynamoTable.prototype._defaultHashKey = function() {
      if (this.isCombinedTable) {
        return this.name + this.combinedHashDelimiter + uuid.v1();
      } else {
        return uuid.v1();
      }
    };

    DynamoTable.prototype._defaultRangeKey = function() {
      return Date.now();
    };

    DynamoTable.prototype._convertValue = function(val, type) {
      switch (type.toUpperCase()) {
        case "N":
          return parseFloat(val, 10);
        case "S":
          if (val) {
            return val.toString(val);
          }
          break;
        default:
          return val;
      }
    };

    DynamoTable.prototype._checkSetOptions = function(type, _upd, attributes, options) {
      var _pred;
      if (type === "create" && (!(options != null ? options.overwriteExistingHash : void 0) || !this.overwriteExistingHash)) {
        _pred = {};
        _pred[this.hashKey] = {
          "==": null
        };
        _upd.when(_pred);
      }
      if (type === "update") {
        if (!_.isEmpty(options.conditionals)) {
          _upd.when(options.conditionals);
        }
      }
      return _upd;
    };

    DynamoTable.prototype._generate = function(cb) {
      var _cr,
        _this = this;
      _cr = this.mng.client.add({
        name: this.tableName,
        throughput: this._getThroughput(),
        schema: this._getShema()
      });
      _cr.save(function(err, _table) {
        if (err) {
          cb(err);
        } else {
          _this.emit("create-status", "waiting");
          _table.watch(function(err, _table) {
            if (err) {
              cb(err);
            } else {
              _this.emit("create-status", "active");
              _this.external = _table;
              cb(null, _table);
            }
          });
        }
      });
    };

    DynamoTable.prototype._getShema = function() {
      var oShema, _hName, _hType, _rName, _rType;
      oShema = {};
      _hName = this.hashKey;
      _hType = this.hashKeyType;
      oShema[_hName] = _hType === "S" ? String : Number;
      if (this.hasRange) {
        _rName = this.rangeKey;
        _rType = this.rangeKeyType;
        oShema[_rName] = _rType === "S" ? String : Number;
      }
      return oShema;
    };

    DynamoTable.prototype._getThroughput = function() {
      var oRet, _ref, _ref1, _ref2, _ref3;
      oRet = this.defaults.throughput;
      if (((_ref = this.options) != null ? (_ref1 = _ref.throughput) != null ? _ref1.read : void 0 : void 0) != null) {
        oRet.read = this.options.throughput.read;
      }
      if (((_ref2 = this.options) != null ? (_ref3 = _ref2.throughput) != null ? _ref3.write : void 0 : void 0) != null) {
        oRet.write = this.options.throughput.write;
      }
      return oRet;
    };

    DynamoTable.prototype.scan = function(_table, query, cb) {
      var _this = this;
      this.fetchTable(_table, function(err, table) {
        var scan;
        scan = table.scan(query);
        scan.fetch(function(err, data) {
          if (err) {
            cb(err);
          } else {
            cb(null, data);
          }
        });
      });
    };

    return DynamoTable;

  })(EventEmitter);

  ERRORMAPPING = {
    "com.amazonaws.dynamodb.v20111205#ConditionalCheckFailedException": {
      name: "conditional-check-failed",
      message: "This is not a valid request. It doesnt match the conditions or you tried to insert a existing hash."
    }
  };

}).call(this);
