// Generated by CoffeeScript 1.3.3
(function() {
  var crudTest;

  crudTest = require("./_incl/crud_test.js");

  crudTest("Basic Table", "Employees", "Todos", "Logs1", "Logs2", "Rooms");

}).call(this);
