# # SimpledynamoManager

# ### extends [NPM:MPBasic](https://cdn.rawgit.com/mpneuried/mpbaisc/master/_docs/index.coffee.html)

#
# ### Exports: *Class*
#
# Main Module
#

Table = require( "./table" )

class SimpleDynamoManager extends require( "./basic" )
	# ## defaults
	defaults: =>
		@extend super,
			# **SimpleDynamoManager.throughput** *Object* The default throughput configuration if a tabele is generated by simple-dynamo
			throughput:
				# **SimpleDynamoManager.throughput.read** *Number* The AWS-DynamoDB read throughput
				read: 5
				# **SimpleDynamoManager.throughput.write** *Number* The AWS-DynamoDB write throughput
				write: 5
			# **SimpleDynamoManager.overwriteExistingHash** *Boolean* Overwrite existing hashed by default
			overwriteExistingHash: false
	###
	## constructor
	###
	constructor: ( options, tables ) ->
		super( options )
		
		@ready = false
		@connected = false
		@fetched = false
		
		@config.manager = @
		
		@TABLES = {}
		
		for tblname, tblconf of tables
			tblconf.key = tblname
			@addTable( tblconf )
		
		return
	
	addTable: ( tbl )=>
		
		if not ( tbl instanceof Table )
			tbl = new Table( tbl, @config )
		
		if @TABLES[ tbl.name ]?
			@_handleError( "addReader", "ETABLEEXISTS", { tablename: tbl.name } )
			return
		
		@TABLES[ tbl.name ] = tbl
		
		tbl.connect() unless tbl.connected
		
		@info "table ´#{tbl.name}´ added"
		return
		
	connect: ( cb )=>
		
		return
		
	ERRORS: =>
		return @extend {}, super,
			# Exceptions
			"ETABLEEXISTS": [ 409, "A table of name `<%=tablename%>` allready exists" ]
			"ETABLENOTFOUND": [ 404, "The table of name `<%=tablename%>` was not found" ]


#export this class
module.exports = SimpleDynamoManager
